// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

const kids = [
  {
    name: "Emma",
    surname: "Johnson",
    age: 7,
    country: "United States",
    sex: "Female",
  },
  {
    name: "Liam",
    surname: "Smith",
    age: 6,
    country: "Canada",
    sex: "Male",
  },
  {
    name: "Olivia",
    surname: "Martinez",
    age: 8,
    country: "Mexico",
    sex: "Female",
  },
  {
    name: "Noah",
    surname: "Chen",
    age: 7,
    country: "China",
    sex: "Male",
  },
  {
    name: "Ava",
    surname: "Garcia",
    age: 6,
    country: "Spain",
    sex: "Female",
  },
  {
    name: "Isabella",
    surname: "Lee",
    age: 9,
    country: "South Korea",
    sex: "Female",
  },
  {
    name: "Sophia",
    surname: "Wang",
    age: 7,
    country: "Australia",
    sex: "Female",
  },
  {
    name: "Mia",
    surname: "Brown",
    age: 6,
    country: "United Kingdom",
    sex: "Female",
  },
  {
    name: "Lucas",
    surname: "Wilson",
    age: 8,
    country: "Canada",
    sex: "Male",
  },
  {
    name: "Liam",
    surname: "Chen",
    age: 7,
    country: "China",
    sex: "Male",
  },
  {
    name: "Aiden",
    surname: "Garcia",
    age: 6,
    country: "Mexico",
    sex: "Male",
  },
  {
    name: "Caden",
    surname: "Anderson",
    age: 8,
    country: "United States",
    sex: "Male",
  },
  {
    name: "Leah",
    surname: "Kim",
    age: 7,
    country: "South Korea",
    sex: "Female",
  },
  {
    name: "Zoe",
    surname: "Smith",
    age: 6,
    country: "Australia",
    sex: "Female",
  },
  {
    name: "Henry",
    surname: "Johnson",
    age: 9,
    country: "United Kingdom",
    sex: "Male",
  },
  {
    name: "Ella",
    surname: "Davis",
    age: 7,
    country: "Canada",
    sex: "Female",
  },
  {
    name: "Aria",
    surname: "Martinez",
    age: 6,
    country: "Mexico",
    sex: "Female",
  },
  {
    name: "Ethan",
    surname: "Chen",
    age: 8,
    country: "China",
    sex: "Male",
  },
  {
    name: "Lily",
    surname: "Garcia",
    age: 7,
    country: "Spain",
    sex: "Female",
  },
  {
    name: "Alexander",
    surname: "Lee",
    age: 6,
    country: "South Korea",
    sex: "Male",
  },
  {
    name: "Mason",
    surname: "Wang",
    age: 8,
    country: "Australia",
    sex: "Male",
  },
  {
    name: "Charlotte",
    surname: "Brown",
    age: 7,
    country: "United Kingdom",
    sex: "Female",
  },
  {
    name: "Sebastian",
    surname: "Wilson",
    age: 6,
    country: "Canada",
    sex: "Male",
  },
  {
    name: "Amelia",
    surname: "Chen",
    age: 8,
    country: "China",
    sex: "Female",
  },
  {
    name: "Harper",
    surname: "Garcia",
    age: 7,
    country: "Mexico",
    sex: "Female",
  },
  {
    name: "Evelyn",
    surname: "Anderson",
    age: 6,
    country: "United States",
    sex: "Female",
  },
  {
    name: "Michael",
    surname: "Kim",
    age: 8,
    country: "South Korea",
    sex: "Male",
  },
  {
    name: "William",
    surname: "Smith",
    age: 7,
    country: "Australia",
    sex: "Male",
  },
  {
    name: "James",
    surname: "Johnson",
    age: 6,
    country: "United Kingdom",
    sex: "Male",
  },
  {
    name: "Sophia",
    surname: "Davis",
    age: 8,
    country: "Canada",
    sex: "Female",
  },
  {
    name: "Oliver",
    surname: "Martinez",
    age: 7,
    country: "Mexico",
    sex: "Male",
  },
  {
    name: "Benjamin",
    surname: "Chen",
    age: 6,
    country: "China",
    sex: "Male",
  },
  {
    name: "Charlotte",
    surname: "Garcia",
    age: 8,
    country: "Spain",
    sex: "Female",
  },
  {
    name: "Ava",
    surname: "Lee",
    age: 7,
    country: "South Korea",
    sex: "Female",
  },
  {
    name: "Liam",
    surname: "Wang",
    age: 6,
    country: "Australia",
    sex: "Male",
  },
  {
    name: "Mia",
    surname: "Brown",
    age: 8,
    country: "United Kingdom",
    sex: "Female",
  },
  {
    name: "Lucas",
    surname: "Wilson",
    age: 7,
    country: "Canada",
  },
];

export default function handler(req, res) {
  res.status(200).json(kids);
}
